# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(340, 590)
        self.textEdit = QtWidgets.QTextEdit(Calculator)
        self.textEdit.setGeometry(QtCore.QRect(10, 60, 321, 81))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Calculator)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Calculator)
        self.widget.setGeometry(QtCore.QRect(10, 170, 323, 410))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_22 = QtWidgets.QPushButton(self.widget)
        self.pushButton_22.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_6.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.widget)
        self.pushButton_23.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_6.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.widget)
        self.pushButton_24.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_6.addWidget(self.pushButton_24)
        self.pushButton_25 = QtWidgets.QPushButton(self.widget)
        self.pushButton_25.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_6.addWidget(self.pushButton_25)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_18 = QtWidgets.QPushButton(self.widget)
        self.pushButton_18.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_5.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.widget)
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_5.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.widget)
        self.pushButton_20.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_5.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.widget)
        self.pushButton_21.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_5.addWidget(self.pushButton_21)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_4.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_4.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.widget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_4.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_4.addWidget(self.pushButton_17)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_3.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_3.addWidget(self.pushButton_13)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Form"))
        self.pushButton.setText(_translate("Calculator", "S"))
        self.pushButton_22.setText(_translate("Calculator", "C"))
        self.pushButton_23.setText(_translate("Calculator", "CE"))
        self.pushButton_24.setText(_translate("Calculator", "^"))
        self.pushButton_25.setText(_translate("Calculator", "DEL"))
        self.pushButton_18.setText(_translate("Calculator", "("))
        self.pushButton_19.setText(_translate("Calculator", ")"))
        self.pushButton_20.setText(_translate("Calculator", "%"))
        self.pushButton_21.setText(_translate("Calculator", "/"))
        self.pushButton_14.setText(_translate("Calculator", "7"))
        self.pushButton_15.setText(_translate("Calculator", "8"))
        self.pushButton_16.setText(_translate("Calculator", "9"))
        self.pushButton_17.setText(_translate("Calculator", "x"))
        self.pushButton_10.setText(_translate("Calculator", "4"))
        self.pushButton_11.setText(_translate("Calculator", "5"))
        self.pushButton_12.setText(_translate("Calculator", "6"))
        self.pushButton_13.setText(_translate("Calculator", "-"))
        self.pushButton_6.setText(_translate("Calculator", "1"))
        self.pushButton_7.setText(_translate("Calculator", "2"))
        self.pushButton_8.setText(_translate("Calculator", "3"))
        self.pushButton_9.setText(_translate("Calculator", "+"))
        self.pushButton_2.setText(_translate("Calculator", "+/-"))
        self.pushButton_3.setText(_translate("Calculator", "0"))
        self.pushButton_4.setText(_translate("Calculator", "."))
        self.pushButton_5.setText(_translate("Calculator", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QWidget()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())
